"""The capability contract is enforced here, not just published.

``scripts/capability_contract.py`` writes ``docs/capability-contract.md`` by unioning a static scan
with a recorded test run. That measurement needs a subprocess and so cannot happen inside pytest;
what *can* happen here is the assertion that matters day to day: the committed artifact still
describes the capabilities the code declares, exactly once each, with a stated reason.

Adding a logical table to the resolver without regenerating the artifact fails this test. So does
deleting one and leaving its row behind, and so does a ``from_logical=`` reader naming a capability
the resolver never declared - which would fail at runtime rather than here.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from mcp_server_sapbw.core.capabilities import ABAP_TABLES, DISCOVER_PATTERNS, HANA_VIEWS

_ROOT = Path(__file__).resolve().parent.parent
_CONTRACT = _ROOT / "docs" / "capability-contract.md"
_SRC = _ROOT / "src" / "mcp_server_sapbw"

# Mirrors STATES in the generator. Duplicated deliberately: if the generator's list changes, this
# test should fail and be reviewed rather than silently accept a new state nobody defined.
_STATES = frozenset(
    {"SUPPORTED", "PARTIAL", "DISCOVERY_ONLY", "PLANNED", "NOT_SUPPORTED", "DEPRECATED"}
)
_REGENERATE = "run: python scripts/capability_contract.py"

_ROW = re.compile(r"^\| `([a-z0-9_]+)` \| `([^`]*)` \| (.*) \|$")
_HEADING = re.compile(r"^## ([A-Z_]+) \((\d+)\)$")


def _declared() -> dict[str, str]:
    return {**ABAP_TABLES, **HANA_VIEWS, **DISCOVER_PATTERNS}


@pytest.fixture(scope="module")
def artifact() -> list[str]:
    assert _CONTRACT.is_file(), f"{_CONTRACT.name} is missing; {_REGENERATE}"
    return _CONTRACT.read_text(encoding="utf-8").splitlines()


@pytest.fixture(scope="module")
def rows(artifact: list[str]) -> dict[str, tuple[str, str, str]]:
    """``{capability: (state, object, reason)}`` parsed out of the artifact's tables."""
    parsed: dict[str, tuple[str, str, str]] = {}
    state = ""
    for line in artifact:
        heading = _HEADING.match(line)
        if heading:
            state = heading.group(1)
            continue
        row = _ROW.match(line)
        if not row:
            continue
        name, obj, reason = row.groups()
        assert name not in parsed, f"`{name}` is listed twice in the contract; {_REGENERATE}"
        parsed[name] = (state, obj, reason.strip())
    return parsed


def test_artifact_is_marked_generated(artifact: list[str]) -> None:
    assert any("GENERATED by scripts/capability_contract.py" in line for line in artifact)


def test_every_declared_capability_has_a_row(rows: dict[str, tuple[str, str, str]]) -> None:
    missing = sorted(set(_declared()) - set(rows))
    assert not missing, f"declared but absent from the contract: {missing}; {_REGENERATE}"


def test_contract_lists_nothing_undeclared(rows: dict[str, tuple[str, str, str]]) -> None:
    stale = sorted(set(rows) - set(_declared()))
    assert not stale, f"in the contract but no longer declared: {stale}; {_REGENERATE}"


def test_every_row_carries_a_known_state_and_a_reason(
    rows: dict[str, tuple[str, str, str]],
) -> None:
    for name, (state, _obj, reason) in sorted(rows.items()):
        assert state in _STATES, f"`{name}` sits under unknown state {state!r}"
        assert reason, f"`{name}` has an empty reason"
        assert "UNDECLARED" not in reason, (
            f"`{name}` is neither read nor given a stated intent. "
            "Implement a reader, or add it to DECLARED_STATE in scripts/capability_contract.py."
        )


def test_row_records_the_physical_object(rows: dict[str, tuple[str, str, str]]) -> None:
    declared = _declared()
    wrong = {n: (o, declared[n]) for n, (_s, o, _r) in rows.items() if o != declared[n]}
    assert not wrong, f"contract names the wrong physical object: {wrong}; {_REGENERATE}"


def test_heading_counts_match_their_sections(
    artifact: list[str], rows: dict[str, tuple[str, str, str]]
) -> None:
    claimed = {m.group(1): int(m.group(2)) for m in map(_HEADING.match, artifact) if m}
    actual: dict[str, int] = {}
    for state, _obj, _reason in rows.values():
        actual[state] = actual.get(state, 0) + 1
    assert claimed == actual, f"section counts disagree with their rows; {_REGENERATE}"


def test_every_from_logical_reader_names_a_declared_capability() -> None:
    """A reader for an undeclared capability raises at runtime. Catch it in the suite instead."""
    blob = "\n".join(p.read_text(encoding="utf-8") for p in sorted(_SRC.rglob("*.py")))
    read = set(re.findall(r'from_logical="([a-z0-9_]+)"', blob))
    unknown = sorted(read - set(_declared()))
    assert not unknown, f"from_logical= names no such capability: {unknown}"
