"""The capability contract is enforced here, not just published.

``scripts/capability_contract.py`` writes ``docs/capability-contract.md`` by unioning a static scan
with a recorded test run. That measurement needs a subprocess and so cannot happen inside pytest;
what *can* happen here is the assertion that matters day to day: the committed artifact still
describes the capabilities the code declares, exactly once each, with a stated reason.

Adding a logical table to the resolver without regenerating the artifact fails this test. So does
deleting one and leaving its row behind, and so does a ``from_logical=`` reader naming a capability
the resolver never declared - which would fail at runtime rather than here.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from mcp_server_sapbw.core.capabilities import (
    ABAP_TABLES,
    DISCOVER_PATTERNS,
    HANA_VIEWS,
    REPO_TABLES,
)
from mcp_server_sapbw.core.contract import contract, contract_revision

_ROOT = Path(__file__).resolve().parent.parent
_CONTRACT = _ROOT / "docs" / "capability-contract.md"
_SRC = _ROOT / "src" / "mcp_server_sapbw"

# Mirrors STATES in the generator. Duplicated deliberately: if the generator's list changes, this
# test should fail and be reviewed rather than silently accept a new state nobody defined.
_STATES = frozenset(
    {"SUPPORTED", "PARTIAL", "DISCOVERY_ONLY", "PLANNED", "NOT_SUPPORTED", "DEPRECATED"}
)
_REGENERATE = "run: python scripts/capability_contract.py"

_VALIDATIONS = frozenset(
    {"not_validated", "unit_tested", "integration_tested", "customer_validated"}
)
# Capability | Object | Validation | Notes
_ROW = re.compile(r"^\| `([a-z0-9_]+)` \| `([^`]*)` \| `([a-z_]+)` \| (.*) \|$")
_HEADING = re.compile(r"^## ([A-Z_]+) \((\d+)\)$")


def _declared() -> dict[str, str]:
    return {**ABAP_TABLES, **HANA_VIEWS, **REPO_TABLES, **DISCOVER_PATTERNS}


@pytest.fixture(scope="module")
def artifact() -> list[str]:
    assert _CONTRACT.is_file(), f"{_CONTRACT.name} is missing; {_REGENERATE}"
    return _CONTRACT.read_text(encoding="utf-8").splitlines()


@pytest.fixture(scope="module")
def rows(artifact: list[str]) -> dict[str, tuple[str, str, str, str]]:
    """``{capability: (state, object, validation, reason)}`` parsed out of the artifact."""
    parsed: dict[str, tuple[str, str, str, str]] = {}
    state = ""
    for line in artifact:
        heading = _HEADING.match(line)
        if heading:
            state = heading.group(1)
            continue
        row = _ROW.match(line)
        if not row:
            continue
        name, obj, validation, reason = row.groups()
        assert name not in parsed, f"`{name}` is listed twice in the contract; {_REGENERATE}"
        parsed[name] = (state, obj, validation, reason.strip())
    return parsed


def test_artifact_is_marked_generated(artifact: list[str]) -> None:
    assert any("GENERATED by scripts/capability_contract.py" in line for line in artifact)


def test_every_declared_capability_has_a_row(rows: dict[str, tuple[str, str, str, str]]) -> None:
    missing = sorted(set(_declared()) - set(rows))
    assert not missing, f"declared but absent from the contract: {missing}; {_REGENERATE}"


def test_contract_lists_nothing_undeclared(rows: dict[str, tuple[str, str, str, str]]) -> None:
    stale = sorted(set(rows) - set(_declared()))
    assert not stale, f"in the contract but no longer declared: {stale}; {_REGENERATE}"


def test_every_row_carries_a_known_state_and_a_reason(
    rows: dict[str, tuple[str, str, str, str]],
) -> None:
    for name, (state, _obj, validation, reason) in sorted(rows.items()):
        assert state in _STATES, f"`{name}` sits under unknown state {state!r}"
        assert validation in _VALIDATIONS, f"`{name}` has unknown validation {validation!r}"
        assert reason, f"`{name}` has an empty reason"
        assert "UNDECLARED" not in reason, (
            f"`{name}` is neither read nor given a stated intent. "
            "Implement a reader, or add it to DECLARED_STATE in scripts/capability_contract.py."
        )


def test_row_records_the_physical_object(rows: dict[str, tuple[str, str, str, str]]) -> None:
    declared = _declared()
    wrong = {n: (o, declared[n]) for n, (_s, o, _v, _r) in rows.items() if o != declared[n]}
    assert not wrong, f"contract names the wrong physical object: {wrong}; {_REGENERATE}"


def test_heading_counts_match_their_sections(
    artifact: list[str], rows: dict[str, tuple[str, str, str, str]]
) -> None:
    claimed = {m.group(1): int(m.group(2)) for m in map(_HEADING.match, artifact) if m}
    actual: dict[str, int] = {}
    for state, _obj, _validation, _reason in rows.values():
        actual[state] = actual.get(state, 0) + 1
    assert claimed == actual, f"section counts disagree with their rows; {_REGENERATE}"


def test_every_from_logical_reader_names_a_declared_capability() -> None:
    """A reader for an undeclared capability raises at runtime. Catch it in the suite instead."""
    blob = "\n".join(p.read_text(encoding="utf-8") for p in sorted(_SRC.rglob("*.py")))
    read = set(re.findall(r'from_logical="([a-z0-9_]+)"', blob))
    unknown = sorted(read - set(_declared()))
    assert not unknown, f"from_logical= names no such capability: {unknown}"


# --- the shipped data file: the same contract, in the form the server reads ------------------


def test_shipped_data_file_matches_the_markdown_artifact(
    rows: dict[str, tuple[str, str, str, str]],
) -> None:
    """One contract, two renderings. A wheel must not disagree with the docs it shipped with."""
    entries = contract()
    assert entries, "capability_contract.json is missing from the package; " + _REGENERATE
    assert set(entries) == set(rows), (
        "the shipped data file and docs/capability-contract.md list different capabilities; "
        + _REGENERATE
    )
    for name, entry in sorted(entries.items()):
        state, obj, validation, reason = rows[name]
        assert (entry.state, entry.object_name, entry.validation) == (state, obj, validation), (
            f"`{name}` disagrees; {_REGENERATE}"
        )
        # The markdown escapes pipes for the table; compare on the unescaped text.
        assert entry.reason.replace("|", "\\|") == reason, f"`{name}` reason differs; {_REGENERATE}"


def test_shipped_contract_carries_a_revision() -> None:
    """Identifies which contract a wheel shipped, so a support answer can cite it."""
    revision = contract_revision()
    assert revision and "+" in revision, f"contract revision is missing or malformed: {revision!r}"


def test_implemented_flag_follows_the_state() -> None:
    entries = contract()
    for name, entry in sorted(entries.items()):
        expected = entry.state in {"SUPPORTED", "PARTIAL", "DISCOVERY_ONLY"}
        assert entry.implemented is expected, f"`{name}`: implemented disagrees with {entry.state}"


# --- two axes: does the code exist, and has it been proven -----------------------------------


def test_implementation_and_state_agree() -> None:
    """``state`` stays because it is a published schema; ``implementation`` is the axis to read."""
    expected = {
        "SUPPORTED": "implemented",
        "PARTIAL": "partial",
        "DISCOVERY_ONLY": "discovery_only",
        "PLANNED": "planned",
        "NOT_SUPPORTED": "unsupported",
        "DEPRECATED": "deprecated",
    }
    for name, entry in sorted(contract().items()):
        assert entry.implementation == expected[entry.state], f"`{name}` axes disagree"


def test_validation_is_never_inferred_from_implementation() -> None:
    """The whole point of the split: being implemented says nothing about being proven.

    If every implemented capability were also validated, the second axis would be decoration.
    """
    entries = contract()
    implemented = [e for e in entries.values() if e.implemented]
    assert implemented, "no implemented capabilities; the fixture assumption is stale"
    unproven = [e for e in implemented if e.validation == "not_validated"]
    assert unproven, (
        "every implemented capability reports as validated, which would mean validation is being "
        "inferred from implementation rather than measured"
    )


def test_nothing_claims_customer_validation_yet() -> None:
    """Stated rather than omitted: it is the honest position, and the gap onboarding closes."""
    claimed = sorted(n for n, e in contract().items() if e.validation == "customer_validated")
    assert not claimed, (
        "a capability claims customer_validated. That claim belongs to a customer verifying it on "
        f"their own system, not to this project: {claimed}"
    )


def test_an_integration_claim_names_the_release_it_was_proven_on() -> None:
    """A validation claim without a release is not a claim: these tables differ across releases."""
    for name, entry in sorted(contract().items()):
        if entry.validation in {"integration_tested", "customer_validated"}:
            assert entry.validated_on, f"`{name}` claims {entry.validation} with no release"
        else:
            assert entry.validated_on is None, (
                f"`{name}` is only {entry.validation} but names a release, which reads as a "
                "stronger claim than it is"
            )


def test_nothing_unread_can_report_unit_tested() -> None:
    """A capability nothing reads cannot have been exercised by a test, by construction."""
    blob = "\n".join(p.read_text(encoding="utf-8") for p in sorted(_SRC.rglob("*.py")))
    static_readers = set(re.findall(r'from_logical="([a-z0-9_]+)"', blob))
    for name, entry in sorted(contract().items()):
        if entry.validation == "unit_tested":
            assert name in static_readers or entry.implemented, (
                f"`{name}` reports unit_tested but nothing reads it"
            )


def test_validation_rank_orders_the_ladder() -> None:
    entries = contract()
    ranks = {e.validation: e.validation_rank for e in entries.values()}
    if "not_validated" in ranks and "integration_tested" in ranks:
        assert ranks["not_validated"] < ranks["integration_tested"]
