"""Shipped data files.

``capability_contract.json`` is generated by ``scripts/capability_contract.py`` and read by
``core.contract``. It is a package resource rather than a repo-relative file so an installed wheel
carries the same contract as a source checkout.
"""
