"""The performance profile, as data the server can read without connecting to anything.

Generated by ``scripts/performance_profile.py`` and shipped inside the package, the same
arrangement the support matrix and capability contract use: measuring a payload means running the
tool surface, which is a build-time activity, so the server consumes the result and never
recomputes it.

Shipping it is the point. "Will this call return on my 40,000-object system, and what will it
cost?" is a question asked *before* there is a profile to connect with, and a bound that only
becomes visible when you hit it is not an answer to it.
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources

from ..models.performance import PerformanceProfile

_DATA_PACKAGE = "mcp_server_sapbw.data"
_DATA_FILE = "performance_profile.json"


@lru_cache(maxsize=1)
def performance_profile() -> PerformanceProfile | None:
    """The shipped profile, or ``None`` when the data file is absent.

    Absence degrades ``bw_performance_profile`` to a stated error and nothing else: the profile
    describes the server, so no metadata reader depends on it.
    """
    try:
        raw = resources.files(_DATA_PACKAGE).joinpath(_DATA_FILE).read_text(encoding="utf-8")
    except (FileNotFoundError, ModuleNotFoundError, TypeError):  # pragma: no cover - packaging
        return None
    payload: dict[str, object] = json.loads(raw)
    # Underscore-prefixed keys are the generator's "do not edit by hand" banner, not schema. The
    # model forbids extras deliberately, so they are dropped here rather than by loosening it.
    return PerformanceProfile.model_validate(
        {k: v for k, v in payload.items() if not k.startswith("_")}
    )
