"""The support matrix, as data the server can read without connecting to anything.

Generated by ``scripts/support_matrix.py`` and shipped inside the package, for the same reason the
capability contract is: establishing it requires running the test suite with per-tool read
attribution switched on, which is a build-time activity. The server consumes it and never recomputes
it.

Shipping it rather than computing it live is the point: this is the one answer a customer needs
*before* there is a profile to connect with. ``bw_support_matrix`` reads it with no BW system in
sight; naming a system afterwards sharpens the answer with that system's discovery record, and is
not a precondition for having one.
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources

from ..models.support import SupportMatrix

_DATA_PACKAGE = "mcp_server_sapbw.data"
_DATA_FILE = "support_matrix.json"


@lru_cache(maxsize=1)
def support_matrix() -> SupportMatrix | None:
    """The shipped matrix, or ``None`` when the data file is absent.

    Absence degrades ``bw_support_matrix`` to a stated error rather than breaking anything else: the
    matrix describes the server, so nothing that reads BW metadata depends on it.
    """
    try:
        raw = resources.files(_DATA_PACKAGE).joinpath(_DATA_FILE).read_text(encoding="utf-8")
    except (FileNotFoundError, ModuleNotFoundError, TypeError):  # pragma: no cover - packaging
        return None
    payload: dict[str, object] = json.loads(raw)
    # Underscore-prefixed keys are the generator's own notes to a human reading the file - the
    # "do not edit by hand" banner. They are not part of the schema, and the model forbids extras on
    # purpose, so they are dropped here rather than by loosening the model for everyone.
    return SupportMatrix.model_validate({k: v for k, v in payload.items() if not k.startswith("_")})
